server:
  port: 10011
  max-http-header-size: 8192
  tomcat:
    accesslog:
      enabled: true
      directory: access_log
      prefix: access_log
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" "%{X-Forwarded-For}i" "%{X-Real-IP}i" %D %S "%U" %v'
    basedir: ./
spring:
  application:
    name: face-recognition
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    username: username # 你的数据库用户名
    password: password # 你的数据库密码，url中添加数据库地址和端口
    url: jdbc:mysql://ip:port/face?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        globally_quoted_identifiers: true
